apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-service
  labels:
    app: cpu-service
spec:
  replicas: 1
  # 使用預設的 RollingUpdate 策略
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       # 更新時可以多出一個臨時 Pod
      maxUnavailable: 0 # 保證隨時都有 1 個 Pod 在運行
  selector:
    matchLabels:
      app: cpu-service
  template:
    metadata:
      labels:
        app: cpu-service
    spec:
      containers:
      - name: cpu-service
        image: allen70429/cpu-service:cc92859
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-service
spec:
  selector:
    app: cpu-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
